### ISSUE TITLE
Sensors unavailable

### ISSUE THREAD

**Issue by Flashlab2** [MvRens/ha-enever#5]
Since today the sensors for my supplier turn into unavailable status within seconds of enabling the integration. 

Supplier: Nextenergy

**Comment by MvRens** [comment]
Thanks for reporting, I noticed it too this afternoon and there seems to be an issue on Enever.nl. When I was testing it, there was no price data specifically for 5 and 6 this morning. This caused the sensor to become unavailable entirely even during hours in which data was present, which I have fixed in version 1.3.2.

However, it is likely that the update will still not result in price data at the moment, as the feed is completely empty now. The website also does not show any electricity prices.

**Comment by Flashlab2** [comment]
Thank you for the quick reply and fix!

Let’s see what tomorrow brings regarding the Enever data.

**Comment by Flashlab2** [comment]
It's still not working even though enever.nl seems to show prices.

**Comment by MvRens** [comment]
You could try to reload the integration, see if that fixes it. I am working on a way to force a refresh. But if you have a free token, you may have also run into issue #6.

Sorry for the inconvenience!

**Comment by Flashlab2** [comment]
I have made a new token on a different email address but unfortunately still all sensors render unavailable.

**Comment by Flashlab2** [comment]
With a new token I managed to get it working again.

**Comment by Flashlab2** [comment]
New week, but no dice unfortunately. I can check on the enever.nl site that my token still has 200+ polls left but still the sensors render unavailable.

**Comment by MvRens** [comment]
Mhhh, can you go into the Settings to System - Logs and see if there is any errors for the Enever integration?

**Comment by Flashlab2** [comment]
Yes, there is log:

```
Deze fout is ontstaan door een aangepaste integratie.

Logger: custom_components.enever.coordinator
Bron: helpers/update_coordinator.py:380
integratie: Enever (documentatie)
Eerst voorgekomen: 08:24:53 (4 gebeurtenissen)
Laatst gelogd: 08:24:58

Unexpected error fetching enever data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 380, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/enever/coordinator.py", line 164, in _async_update_data
    response = await self._fetch_today()
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/enever/coordinator.py", line 255, in _fetch_today
    return await self.api.gasprijs_vandaag()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/enever/enever_api.py", line 173, in gasprijs_vandaag
    return await self._fetch_parsed(self.ENDPOINT_GASPRIJS_VANDAAG)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/enever/enever_api.py", line 186, in _fetch_parsed
    raise EneverError(
        "Unexpected code in response: " + response_payload["code"]
    )
custom_components.enever.enever_api.EneverError: Unexpected code in response: 3
```

**Comment by MvRens** [comment]
Thanks for the log! I can't find what the different response codes mean. 2 appears to be "invalid API token" but I haven't encountered 3 yet myself. So I've removed the check in favor of examining the data that is returned. If there's still an error at least now it should show up in the logs with a proper description.

Can you replace your enever_api.py file with the new one at https://github.com/MvRens/ha-enever/blob/develop/custom_components/enever/enever_api.py and restart HA? Thanks!

**Comment by Flashlab2** [comment]
```
Deze fout is ontstaan door een aangepaste integratie.

Logger: custom_components.enever.coordinator
Bron: helpers/update_coordinator.py:380
integratie: Enever (documentatie)
Eerst voorgekomen: 12:57:33 (4 gebeurtenissen)
Laatst gelogd: 12:57:38

Unexpected error fetching enever data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 380, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/enever/coordinator.py", line 164, in _async_update_data
    response = await self._fetch_today()
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/enever/coordinator.py", line 281, in _fetch_today
    return await self.api.stroomprijs_vandaag()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/enever/enever_api.py", line 165, in stroomprijs_vandaag
    return await self._fetch_parsed(self.ENDPOINT_STROOMPRIJS_VANDAAG)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/enever/enever_api.py", line 190, in _fetch_parsed
    raise EneverError(
    ...<2 lines>...
    )
custom_components.enever.enever_api.EneverError: Invalid data element in response: API token deactivated. Contact us via the contact form
```

**Comment by Flashlab2** [comment]
It seems the error is not in the Integration but in the token. That's weird as the token is active and does give feedback from the enever.nl site.

**Comment by MvRens** [comment]
Well, at least the error message is clear now.
Do you get a valid response if you open the feed in your browser? 

https://enever.nl/api/stroomprijs_vandaag.php?token=<token>

A possibility is that it was deactivated because they detected that you've created a second token, which is against the policy. You'd have to contact them to be sure though.

**Comment by Flashlab2** [comment]
Well I tried to contact them after I decided to support Enever by donating but it seems I got banned instead. Yes I did open an extra token to bug check this integration so I guess it's my fault anyway.

No answer though on the support mail but at least I got part of my donation back. I would rather have had a normal answer back and then I'd let them keep the donation as I do feel that Enever provides a good service. Too bad for me but I hope other people can use your excellent HA integration!

I guess you close this topic now. Thank you for your help!
